name: pmc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get: ^4.6.6
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  video_player: ^2.9.2
  percent_indicator: ^4.2.3
  flick_video_player: ^0.9.0
  http: ^1.2.2
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.3
  firebase_core: ^3.4.0
  image_picker: ^1.1.2
  firebase_auth: ^5.2.0
  flutter_stripe: ^11.1.0
  html: ^0.15.5
  youtube_player_flutter: ^9.1.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.1.5
  insta_image_viewer: ^1.0.4
  razorpay_flutter: ^1.3.7
  awesome_dialog: ^3.1.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  telephony_fix: ^0.2.1
  dio: ^5.0.3


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
