// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf5h4PKgqxq5pLaenXyGdcIzoflJOIPE4',
    appId: '1:111042309336:web:16802b60ac731e9339fbad',
    messagingSenderId: '111042309336',
    projectId: 'pickmycourse-8cc02',
    authDomain: 'pickmycourse-8cc02.firebaseapp.com',
    storageBucket: 'pickmycourse-8cc02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5zJKy9IoW29ZPX6yVdzCSHSGct-aywQ',
    appId: '1:111042309336:android:c6f0c55900e2c86439fbad',
    messagingSenderId: '111042309336',
    projectId: 'pickmycourse-8cc02',
    storageBucket: 'pickmycourse-8cc02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2QphTTQV69UlpvNlMGHVnqzA9Bv9F2I',
    appId: '1:111042309336:ios:5f123b66722aaf1d39fbad',
    messagingSenderId: '111042309336',
    projectId: 'pickmycourse-8cc02',
    storageBucket: 'pickmycourse-8cc02.firebasestorage.app',
    iosBundleId: 'com.example.pmc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2QphTTQV69UlpvNlMGHVnqzA9Bv9F2I',
    appId: '1:111042309336:ios:5f123b66722aaf1d39fbad',
    messagingSenderId: '111042309336',
    projectId: 'pickmycourse-8cc02',
    storageBucket: 'pickmycourse-8cc02.firebasestorage.app',
    iosBundleId: 'com.example.pmc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf5h4PKgqxq5pLaenXyGdcIzoflJOIPE4',
    appId: '1:111042309336:web:32dfe87211c6f53439fbad',
    messagingSenderId: '111042309336',
    projectId: 'pickmycourse-8cc02',
    authDomain: 'pickmycourse-8cc02.firebaseapp.com',
    storageBucket: 'pickmycourse-8cc02.firebasestorage.app',
  );
}
